title: PatchyPython
description: Python for beginners, experts, and everyone in between
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme 
relative_links:
  enabled: true
  collections: true
